const universities=[
{id:"psu",name:"Pitirim Sorokin Syktyvkar State University",city:"Syktyvkar",course:"Medicine",medium:"English",scholarship:"yes",status:"verified",tuition:"Verify official fee",hostel:"Verify official fee"},
{id:"kfu",name:"Kazan Federal University",city:"Kazan",course:"Medicine",medium:"English",scholarship:"yes",status:"verified",tuition:"Verify official fee",hostel:"Verify official fee"},
{id:"kntu",name:"Kazan National Research Technical University",city:"Kazan",course:"Engineering",medium:"Russian",scholarship:"yes",status:"pending",tuition:"Verify official fee",hostel:"Verify official fee"},
{id:"mit",name:"Moscow Institute of Technology",city:"Moscow",course:"IT",medium:"Russian",scholarship:"no",status:"pending",tuition:"Verify official fee",hostel:"Verify official fee"},
{id:"spbu",name:"Saint Petersburg State University",city:"Saint Petersburg",course:"Business",medium:"Russian",scholarship:"yes",status:"pending",tuition:"Verify official fee",hostel:"Verify official fee"}];
let selected=[];
const $=s=>document.querySelector(s);
function render(){let c=$("#course").value,city=$("#city").value,m=$("#medium").value,s=$("#scholarship").value;let data=universities.filter(u=>(!c||u.course===c)&&(!city||u.city===city)&&(!m||u.medium===m)&&(!s||u.scholarship===s));$("#count").textContent=data.length;$("#cards").innerHTML=data.map(u=>`<article class="card"><div class="card-top"><span class="tag ${u.status==="verified"?"verified":"pending"}">${u.status==="verified"?"VERIFIED RECORD":"CONFIRM DATA"}</span><span class="tag">${u.course}</span></div><h3>${u.name}</h3><div class="location">${u.city} · ${u.medium}</div><div class="facts"><div><small>TUITION</small><b>${u.tuition}</b></div><div><small>HOSTEL</small><b>${u.hostel}</b></div><div><small>SCHOLARSHIP</small><b>${u.scholarship==="yes"?"Listed":"Not listed"}</b></div></div><button onclick="toggle('${u.id}')">${selected.includes(u.id)?"Added ✓":"+ Compare"}</button></article>`).join("")}
function toggle(id){if(selected.includes(id))selected=selected.filter(x=>x!==id);else if(selected.length<3)selected.push(id);else return alert("Choose up to 3.");render();compare()}
function compare(){if(!selected.length){$("#compareBox").textContent="Your comparison will appear here.";return}let d=selected.map(id=>universities.find(u=>u.id===id));$("#compareBox").innerHTML=`<table class="compare-table"><tr><th>Metric</th>${d.map(u=>`<th>${u.name}</th>`).join("")}</tr><tr><td>City</td>${d.map(u=>`<td>${u.city}</td>`).join("")}</tr><tr><td>Course</td>${d.map(u=>`<td>${u.course}</td>`).join("")}</tr><tr><td>Medium</td>${d.map(u=>`<td>${u.medium}</td>`).join("")}</tr><tr><td>Scholarship</td>${d.map(u=>`<td>${u.scholarship==="yes"?"Listed":"Not listed"}</td>`).join("")}</tr><tr><td>Data status</td>${d.map(u=>`<td>${u.status==="verified"?"Verified record":"Confirmation required"}</td>`).join("")}</tr></table>`}
["course","city","medium","scholarship"].forEach(id=>$("#"+id).addEventListener("change",render));
function money(v){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v)}
function calc(){let t=+$("#tuition").value||0,h=+$("#hostel").value||0,l=(+$("#living").value||0)*12,i=+$("#insurance").value||0,o=+$("#other").value||0,ini=+$("#initial").value||0,y=+$("#years").value||1,r=+$("#rate").value||1;let a=(t+h+l+i+o)*r;$("#annual").textContent=money(a);$("#total").textContent=money(((t+h+l+i+o)*y+ini)*r)}
["tuition","hostel","living","insurance","other","initial","years","rate"].forEach(id=>$("#"+id).addEventListener("input",calc));render();compare();calc();
